---
- name: Install LDAP pip dependencies
  pip:
    name: django-auth-ldap
    virtualenv: "{{ netbox_virtualenv_path }}"

- name: Write LDAP configuration
  template:
    src: "{{ netbox_ldap_config_template }}"
    dest: "{{ netbox_config_path }}/ldap_config.py"
    mode: 0600
  notify:
    - reload netbox
