---
- name: Configure netbox
  template:
    src: templates/configuration.py.j2
    dest: "{{ netbox_shared_path }}/configuration.py"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: 0640

- name: Create a link for configuration.py
  file: 
    src: "{{ netbox_shared_path }}/configuration.py"
    dest: "{{ netbox_config_path }}/configuration.py"
    state: link

- name: Run DB migrations
  django_manage:
    command: migrate
    app_path: "{{ netbox_current_path }}/netbox"
    virtualenv: "{{ netbox_venv_path }}"
  become_user: "{{ netbox_database_user }}"

- name: Collect Static Files
  django_manage:
    command: collectstatic --no-input
    app_path: "{{ netbox_current_path }}/netbox"
    virtualenv: "{{ netbox_venv_path }}"

- name: Load initial Data (optional)
  django_manage:
    command: loaddata initial_data
    app_path: "{{ netbox_current_path }}/netbox"
    virtualenv: "{{ netbox_venv_path }}"
  become_user: "{{ netbox_database_user }}"
