---
- name: Download and untar NetBox tarball
  unarchive:
    src: "{{ netbox_stable_uri }}"
    dest: "{{ netbox_releases_path }}"
    copy: no
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
  when: netbox_stable 

- name: Create a link to active release
  file:
    src: "{{ netbox_releases_path }}/netbox-{{ netbox_stable_release }}"
    dest: "{{ netbox_current_path }}"
    state: link
  when: netbox_stable

- name: Clone netbox.git
  git:
    repo: "{{ netbox_git_uri }}"
    dest: "{{ netbox_git_path }}"
  when: netbox_git 

- name: Create a link for git
  file:
    src: "{{ netbox_git_path }}"
    dest: "{{ netbox_current_path }}"
    state: link
  when: netbox_git
