---
# tasks file for lae.netbox
- include: check_mandatory_vars.yml

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- include: "install_packages_{{ ansible_pkg_mgr }}.yml"

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    state: latest
    executable: "{{ netbox_pip3_binary if (netbox_python == 3) else netbox_pip2_binary }}"

- name: Create NetBox user group
  group:
    name: "{{ netbox_group }}"

- name: Create NetBox user and home directory
  user:
    name: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    home: "{{ netbox_home }}"

- name: Create NetBox deployment directories
  file: 
    path: "{{ item }}" 
    state: directory
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
  with_items:
    - "{{ netbox_releases_path }}"
    - "{{ netbox_shared_path }}"
    - "{{ netbox_git_path }}"

- include: download_netbox_tarball.yml
  when: netbox_stable == true

- name: Install Netbox python dependencies inside active virtualenv
  pip:
    requirements: "{{ netbox_current_path }}/requirements.txt"
    virtualenv: "{{ netbox_current_path }}/venv-py{{ netbox_python }}"
    virtualenv_python: "{{ netbox_python3_binary if (netbox_python == 3) else netbox_python2_binary }}"
  when: netbox_stable

# This is inside a block to be able to use become_user correctly
- block:
  - name: Ensure Postgres database exists (via socket)
    postgresql_db:
      name: "{{ netbox_database }}"
      login_user: "{{ netbox_database_user }}"
      login_unix_socket: "{{ netbox_database_socket }}"
    become: True
    become_user: "{{ netbox_database_user }}"
  when:
    - netbox_database_socket is defined
    - netbox_database_host is not defined

- name: Ensure Postgres database exists (via TCP)
  postgresql_db:
    name: "{{ netbox_database }}"
    login_host: "{{ netbox_database_host }}"
    login_port: "{{ netbox_database_port }}"
    login_user: "{{ netbox_database_user }}"
    login_password: "{{ netbox_database_password }}"
  when:
    - netbox_database_socket is not defined
    - netbox_database_host is defined

- name: Postgres template and configuration 
  include: configuration.yml
  when: netbox_stable
