---
# handlers file for lae.netbox
- name: restart netbox.socket
  systemd:
    name: netbox.socket
    state: restarted

- name: restart netbox.service after daemon-reload
  systemd:
    name: netbox.service
    state: restarted
    daemon_reload: yes

- name: reload netbox.service
  systemd:
    name: netbox.service
    state: reloaded
